name: Render and Publish
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up R  # Add this step
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2'  # or whatever version you prefer
          
      - name: Install R packages  # Add this step if you use packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: docs
          
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs
          
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
